shellEmulator: true
shamefullyHoist: true
strictPeerDependencies: true

trustPolicy: no-downgrade

overrides:
  semver@6: 6.3.0
  "workbox-build@7.4.0>rollup": 2.79.2
  workbox-build: 7.4.0

peerDependencyRules:
  allowedVersions:
    eslint: ">=8.57.0"

allowBuilds:
  "@parcel/watcher": true
  "@tailwindcss/oxide": true
  better-sqlite3: true
  esbuild: true
  rollup: true
  sharp: true
  unrs-resolver: true
  vue-demi: true
  workerd: true
